# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 759cd91e62d1b0a2e34a9c03d04159985d307f1e06a17bc25b98242f9023b7bb95d5897d225036b243b9f079ef4eb1ac0a15a247d9de866a79396b3800f878f9

test:
  secret_key_base: 3dceb5e115075ee2e2b88a019999021cbf96a3b806227819937abf549f41aa37db46624e9c2ae101feba2444ad9ceb1f1f6a7fb785234e135c36bb4b36ed4f5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
